### ISSUE TITLE
js收官中的问题

### ISSUE THREAD

**Issue by cheer001** [gerrykf/front_end-path#2]
js收官中  流程分割里面的题是接近实际开发的

**Comment by gerrykf** [comment]
是的

**Comment by gerrykf** [comment]
详情请参考：
https://github.com/gerrykf/front_end-path/blob/main/%E6%8A%80%E6%9C%AF%E5%BA%94%E7%94%A8%E9%98%B6%E6%AE%B5/JS%E6%94%B6%E5%AE%98/%E6%B5%81%E7%A8%8B%E7%9A%84%E5%88%86%E5%89%B2.js
